import type { Metadata } from "next";

import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-[#FCFDFE] overflow-hidden">
      <section className="bg-shade_03 sm:pt-10 pt-8 sm:pb-[50px] pb-5">
        <div className="xl:max-w-[1228px] sm:mb-0 mb-5 max-w-[1000px] mx-auto px-4 md:flex gap-5 items-center">
          <div className="xl:w-4/12 md:w-5/12 w-full flex flex-col items-center sm:items-start  ">
            <h1 className="text-neutral_07 tracking-[-2.4px] font-poppins font-semibold lg:text-[60px] md:text-[55px] text-[48px] text-center sm:text-left sm:leading-[64px] leading-[56px] sm:mb-4 mb-2">
              Join Us to Redefine the Ordinary
            </h1>
            <p className="text-neutral_04 font-poppins md:max-w-[356px] w-full font-medium xl:text-[28px] lg:text-[22px] sm:text-[20px] text-center sm:text-left  text-base sm:leading-[32px] leading-7 tracking-[-1%] sm:mb-[40px] mb-2.5">
              Build the future with tech. Disrupt the ordinary with creativity.
              Let’s create something amazing — together.
            </p>
            <Link
              href="https://www.104.com.tw/company/1a2x6bn9wd?jobsource=cd_my104_view_r"
              target="_blank"
              className="bg-color_01 hover:bg-shade_06 w-[172px] h-12 flex justify-center items-center  rounded-[48px] font-semibold font-poppins text-sm text-neutral_01"
            >
              {" "}
              Come join us now{" "}
            </Link>
          </div>
          <div className="md:w-8/12 w-full xl:-ml-12 sm:mt-0 mt-4">
            <div className="xl:mr-0 sm:-mr-20 sm:ml-0 -mx-5">
              <img src="/hero.png" alt="Logo" className="xl:max-w-[inherit]" />
            </div>
          </div>
        </div>
        <Link
          href="#"
          className="sm:flex  sm:text-start text-center items-center justify-center gap-3 text-neutral_04 font-poppins font-medium text-xs mt"
        >
          <span className="bg-neutral_03 sm:mx-0  mx-auto h-6 w-6 flex justify-center items-center rounded-full">
            <svg
              width={8}
              height={8}
              viewBox="0 0 8 8"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M3.97021 1V7.16"
                stroke="#202225"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M3.97021 7.17973L6.44022 4.71973"
                stroke="#202225"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M3.97 7.17973L1.5 4.71973"
                stroke="#202225"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>

          </span>
          <span className="inline-block w-full sm:mt-0 mt-2">Scroll down</span>
        </Link>
      </section>

      <section className="md:pt-[50px] pt-5">
        <div className=" xl:max-w-[1228px] max-w-[976px] sm:mx-auto mx-4 sm:px-4 xl:flex gap-[115px] items-center border-b-2 border-neutral_03 ">
          <div className="xl:w-4/12 w-full">
            <h1 className="text-neutral_07 font-poppins font-semibold xl:text-[60px] leading-[36px] lg:text-5xl md:text-[40px] sm:text-[36px] text-[28px] sm:leading-[64px] md:mb-6 mb-3">
              Where Performance Meets Elegance
            </h1>
            <p className="text-neutral_04 font-poppins font-medium lg:text-[22px] md:text-[20px] sm:text-[18px] text-base sm:mb-[40px] mb-2.5 xl:max-w-[336px] w-full">
              Crafting the perfect balance of speed and elegance — powered by
              Go, designed with React. <br />
              We believe development should be a seamless creative journey:
              clean architecture, clear process, and elegant results.
            </p>
          </div>
          <div className="xl:w-7/12 w-full flex justify-center sm:pb-[58px] pb-8 xl:pb-0">
            <Image
              src="/react.png"
              alt="Logo"
              width={720}
              height={336.51}
              className="hidden sm:block"
            />
            <Image
              src="/react-mobile.png"
              alt="Logo"
              width={205}
              height={433.42}
              className="sm:hidden block"
            />
          </div>
        </div>
      </section>

      <section className="sm:mt-[60px] mt-5 sm:px-4 px-6">
        <h1 className="text-neutral_07  font-poppins lg:text-5xl sm:text-[40px] text-[28px] font-semibold text-center">
          Discover how it work
        </h1>
        <div className="xl:max-w-[1184px] max-w-[976px] mx-auto xl:px-20 xl:pr-0 sm:px-12 px-6 md:mt-[69px] mt-[30px] bg-shade_02 ">
          <div className="max-w-[1026px] mx-auto sm:flex items-center ">
            <div className="sm:w-1/2 w-full  md:pr-[81px] sm:pr-[50px] pt-6 sm:pt-0">
              <h2 className="text-neutral_07 lg:text-4xl sm:text-[32px] text-2xl  font-poppins font-semibold mb-[17px] xl:max-w-[430px] max-w-[335px]">
                Getting Started, the Right Way
              </h2>
              <p className="text-neutral_04 font-poppins font-semibold text-base xl:max-w-[430px] max-w-[335px]">
                We&apos;ve crafted an onboarding experience designed for clarity,
                speed, and connection.
              </p>
            </div>
            <div className="sm:w-1/2 w-full  md:pl-[82px] sm:pl-[50px] xl:pt-[105px] sm:pt-20 pt-16 sm:mt-0 mt-[32px] sm:border-l-2 md:border-t-0 border-t-2 border-neutral_03 sm:pb-[76px] pb-14">
              <div className="flex  justify-between items-center gap-6 xl:gap-0 border-b-2 border-neutral_03 pb-10">
                <div className="flex-1  max-w-[302px]">
                  <h2 className="text-neutral_07  text-base font-poppins font-semibold">
                    Shared materials
                  </h2>
                  <p className="text-neutral_04 text-sm  font-poppins font-medium">
                    Everything you need, already prepared.
                  </p>
                </div>
                <div className="bg-color_05 w-[75px] h-[75px] rounded-full flex justify-center items-center ">
                  <Image
                    src="/envolop.png"
                    alt="Logo"
                    width={48}
                    height={48}
                    className="lg:w-12 w-[39px]"
                  />
                </div>
              </div>
              <div className="flex justify-between items-center border-b-2 gap-6 xl:gap-0 border-neutral_03 xl:py-10 py-8">
                <div className="flex-1 max-w-[302px]">
                  <h2 className="text-neutral_07  text-base font-poppins font-semibold">
                    Live interaction
                  </h2>
                  <p className="text-neutral_04 text-sm  font-poppins font-medium">
                    Your starter kit, docs, and stack—ready from day one.
                  </p>
                </div>
                <div className="bg-color_02 w-[75px] h-[75px] rounded-full flex justify-center items-center ">
                  <Image
                    src="/interaction.png"
                    alt="Logo"
                    width={48}
                    height={48}
                    className="lg:w-12 w-[39px]"
                  />
                </div>
              </div>
              <div className="flex justify-between items-center gap-6 xl:gap-0 xl:pt-10 pt-8">
                <div className="flex-1  max-w-[302px]">
                  <h2 className="text-neutral_07  text-base font-poppins font-semibold">
                    Realtime collaboration
                  </h2>
                  <p className="text-neutral_04 text-sm  font-poppins font-medium">
                    One click to access codebase, design files, and docs.
                  </p>
                </div>
                <div className="bg-color_03 w-[75px] h-[75px] rounded-full flex justify-center items-center ">
                  <Image
                    src="/icon.png"
                    alt="Logo"
                    width={48}
                    height={48}
                    className="lg:w-12 w-[39px]"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="xl:max-w-[1184px] max-w-[976px] mx-auto sm:mt-[63px] mt-[30px] bg-shade_02 relative">
          <div className="max-w-[1026px] xl:px-0 sm:px-12 px-6 mx-auto sm:flex items-stretch relative">
            <div className="sm:w-1/2 w-full flex flex-col  justify-center pt-5 sm:pt-0 sm:pr-5">
              <h2 className="text-neutral_07 lg:text-4xl sm:text-[32px] text-2xl font-poppins font-semibold mb-[17px] max-w-[319px]">
                Milestones & Achievements
              </h2>
              <p className="text-neutral_04 font-poppins font-semibold text-base sm:max-w-[319px]">
                Opportune Soft Ltd. was officially established, with a clear
                vision to become a leading force in the software outsourcing
                industry.
              </p>
            </div>
            <div className="relative flex sm:my-0 my-10 items-center justify-center z-10">
              <div className="static
                  sm:w-[2px] w-full sm:bg-neutral_03 flex sm:flex-col flex-row justify-between items-center gap-6 xl:py-[210px] lg:py-[176px] sm:py-[300px] py-0">
                <div className="w-5 h-5 bg-[#439FFE] rounded-full flex justify-center items-center">
                  <div className="w-[8px] h-[8px] bg-neutral_01 rounded-full shadow-xl"></div>
                </div>
                <div className="w-5 h-5 bg-[#D38BFF] rounded-full"></div>
                <div className="w-5 h-5 bg-[#EF799C] rounded-full"></div>
                <div className="w-5 h-5 bg-[#9DDA6E] rounded-full"></div>
              </div>
              <div className="bg-neutral_03 h-[1px] sm:hidden block absolute top-1/2 -translate-y-1/2 -z-10 left-0 w-full"></div>
            </div>
            <div className="sm:w-1/2 w-full sm:pl-[82px] ">
              <div className="flex sm:justify-center h-full sm:items-center">
                <img src="/group.png" alt="Logo" />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-neutral_02  sm:mt-[62px] mt-5 sm:py-[63px] py-5">
        <div className="px-4">
          <h2 className="text-neutral_07 font-poppins text-5xl font-semibold text-center mb-3 hidden xl:block">
            The Good Stuff
          </h2>
          <h2 className="text-neutral_07 font-poppins xl:text-5xl lg:text-[48px] md:text-[40px] sm:text-[30px] text-[28px] font-semibold text-center mb-3 xl:hidden block">
            People are talking...
          </h2>
          <p className="text-neutral_04 font-poppins xl:text-base lg:text-[18px] text-base font-semibold text-center">
            Perks that keep you happy, healthy, and inspired.
          </p>
        </div>
        <div className="xl:max-w-[1184px] max-w-[1000px] mx-auto sm:px-4 px-6 sm:mt-[54px] mt-[30px] grid md:grid-cols-3  sm:grid-cols-2 grid-cols-1 gap-[22px]">
          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/user-2.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                1, Work from anywhere you thrive — with two days of remote work each week. We care about results, not where you sit.
                <br></br>
                2, No work on make-up days — your weekends stay free.
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              Flexibility is king
            </p>
          </div>
          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/avatar.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                The right tools, your call. From high-end MacBooks to custom setups, we’ll equip you for impact.
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              Upgrading your setup is easy — we’ve got you covered.
            </p>
          </div>
          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/user-3.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                Generous pay, annual bonuses — we believe great work deserves great rewards.
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              When you put in the effort, we double down on your future.
            </p>
          </div>

          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/user-4.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                1, Curious minds welcome — we cover the cost of your learning adventures.<br></br>
                2, Weekly Team Workout, plus a monthly fitness subsidy.
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              Growth Without Limits
            </p>
          </div>
          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/user-5.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                1, Unlimited Snacks & Drinks<br></br>
                2, Extra Time Off (Because Life Matters)<br></br>
                3, Festive Bonuses to Brighten Your Life
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              Everyday life? We keep it chill
            </p>
          </div>
          <div className="bg-neutral_01 flex flex-col justify-between rounded-[16px] pt-12 px-10 py-10">
            <div>
              <Image src="/user-6.png" alt="Logo" width={64} height={64} />
              <p className="text-neutral_04 font-poppins text-base font-medium mb-9 mt-[17px]">
                Video games, board games, escape rooms — we play hard and laugh harder.
              </p>
            </div>
            <p className="text-neutral_07 text-base font-poppins font-semibold">
              Team Building, But Actually Fun
            </p>
          </div>
        </div>
      </section>

    </main>
  );
}
